jdk:
    - oraclejdk8
language: java

before_install:
    - psql -U postgres -c "create extension postgis"
    - psql -c 'create user tdar CREATEDB;' -U postgres
    - psql -c 'create database test_tdardata' -U tdar -d template1
    - psql -c 'create database test_tdarmetadata' -U tdar -d template1
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - jdk_switcher use oraclejdk8

install:
    - mvn -q -Psetup-new-instance install -DskipTests

script:
    - mvn -q -Ptest,start-x-server,minify-web-resources verify

env: DB=postgres MAVEN_OPTS="-Xmx1536m -Xms1024m -XX:MaxPermSize=512m"
