version: '3'
services:
  db:
    image: mdillon/postgis:latest
    ports:
      - 5432:5432
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: tdar
        POSTGRES_USERNAME: tdar
  solr:
    image: solr
    ports:
      - "8983:8983"
    volumes:
       - data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
  web:
    build: .
    image: dataarc/web
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - "8280:8280"
    links:
      - db
      - solr
      
## docker-compose build --pull
## docker-compose up